# Analysis

## Logical Fallacies
 
    Read about the [common fallacies](https://medium.com/@pnhoward/12-common-fallacies-used-in-social-research-9713e4d9bf48) in social research. Summary below:
  
    - fallacies of authority
    - fallacies of logic
    - fallacies of emotion
    
  
## Biases
 
    - Sampling bias
        + e.g., 1948 U.S. presidential election (see this [case study](https://www.math.upenn.edu/~deturck/m170/wk4/lecture/case2.html))
        + even very large samples could have sampling biases if sampling methods are poor and unrepresentative of the population (e.g., [1936 Literary Digest Poll](https://www.math.upenn.edu/~deturck/m170/wk4/lecture/case1.html))
    - Omitted variable bias
    - Nonresponse bias
    - Selection bias
    - Survivorship bias
        + e.g., when bankrupt companies are removed from a stock index and replaced with profitable companies, the index would experience an upward bias. Business failures would not be accounted for in time series data.
    - Recall bias

## Model Selection

  * [Model Selection in R](http://r-statistics.co/Model-Selection-in-R.html)
  * [Linear Model Selection](https://uc-r.github.io/model_selection)

  * Forward/Backward Selection
  * AIC/BIC
  * Nested F-tests
      - model comparisons for linear regressions
  * Likelihood ratio tests
      - model comparisons for generalized linear models
  * Parsimony
